### ISSUE TITLE
PLC Spawner - Skull Candle - Wrong Orientation

### ISSUE THREAD

**Issue by cltalmadge** [amia-team/amia-issues#1]
The Skull Candle spawns facing away from you. It should face toward. (Reported by: BagofFelt)

**Comment by Lord-Jyssev** [comment]
These are a simple fix, as I've updated the base script to allow for modifying spawn rotation. Any errant placeable simply needs a `SpawnRotation` **float** variable added to the PLC on the palette with the degrees it needs to rotate.

Tent, Red and White is one that I've tested that serves as an example!
